# provenance: Human/Claude-authored platform code (engineered, not agent-generated)
"""Deliverable-contract validation for benchmark workspaces.

Every L2/L3 task promises the same machine-checkable contract so any
harness's output is scored identically:

  * the expected artifacts exist,
  * ``report.json`` parses and carries the required metric keys,
  * ``predict.py`` honors the CLI (``--input params.json --output pred.npz``)
    and returns psi shaped (N, 96, 64) on the frozen evaluation grid,
  * (L3 only) no workspace Python file imports ``autotokamak`` — the
    from-scratch condition is audited, not merely requested.

``score_against_frozen`` computes the head-to-head relative-L2 numbers on a
frozen test set generated by ``bench freeze-testset``.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import numpy as np

from autotokamak.bench.taskspec import TaskSpec

# Frozen evaluation grid (matches benchmarks/assets/eval_grid.json and the
# task text): psi is (nZ, nR) = (96, 64).
DEFAULT_GRID = {
    "R": {"n": 64, "low": 0.15, "high": 0.80},
    "Z": {"n": 96, "low": -0.40, "high": 0.40},
}
GRID_ATOL = 1e-9
REQUIRED_REPORT_KEYS = ("n_solves_attempted", "n_solves_succeeded", "metrics")
REQUIRED_METRIC_BLOCKS = ("test_rel_l2", "baseline_rel_l2")
REQUIRED_METRIC_STATS = ("mean", "median", "p90")


@dataclass
class ContractReport:
    """One gate per check; ``passed`` is the AND of all hard gates."""

    gates: dict[str, bool] = field(default_factory=dict)
    notes: dict[str, str] = field(default_factory=dict)

    @property
    def passed(self) -> bool:
        return bool(self.gates) and all(self.gates.values())

    def set(self, gate: str, ok: bool, note: str = "") -> None:
        self.gates[gate] = bool(ok)
        if note:
            self.notes[gate] = note

    def to_dict(self) -> dict[str, Any]:
        return {"passed": self.passed, "gates": self.gates, "notes": self.notes}


def load_grid(grid_json: Optional[Path] = None) -> dict:
    if grid_json is not None and Path(grid_json).is_file():
        return json.loads(Path(grid_json).read_text())
    return DEFAULT_GRID


def grid_axes(grid: dict) -> tuple[np.ndarray, np.ndarray]:
    r = grid["R"]
    z = grid["Z"]
    return (
        np.linspace(float(r["low"]), float(r["high"]), int(r["n"])),
        np.linspace(float(z["low"]), float(z["high"]), int(z["n"])),
    )


def audit_no_autotokamak_import(workspace: Path) -> list[str]:
    """Return every workspace .py file that references autotokamak (L3 gate)."""
    pattern = re.compile(r"^\s*(?:import|from)\s+autotokamak\b", re.MULTILINE)
    offenders: list[str] = []
    for p in sorted(Path(workspace).rglob("*.py")):
        if p.is_symlink() or any(part == "__pycache__" for part in p.parts):
            continue
        try:
            if pattern.search(p.read_text(encoding="utf-8", errors="replace")):
                offenders.append(str(p.relative_to(workspace)))
        except OSError:
            continue
    return offenders


def _check_report_json(report_path: Path, report: ContractReport) -> None:
    try:
        data = json.loads(report_path.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001
        report.set("report_parses", False, f"{type(exc).__name__}: {exc}")
        return
    report.set("report_parses", True)

    missing = [k for k in REQUIRED_REPORT_KEYS if k not in data]
    metrics = data.get("metrics") or {}
    for block in REQUIRED_METRIC_BLOCKS:
        stats = metrics.get(block) or {}
        missing += [
            f"metrics.{block}.{s}" for s in REQUIRED_METRIC_STATS if s not in stats
        ]
    report.set(
        "report_keys", not missing,
        f"missing: {missing}" if missing else "",
    )


def run_predict(
    workspace: Path,
    params: list[dict],
    *,
    timeout_seconds: int = 600,
    python: str = sys.executable,
) -> dict[str, np.ndarray]:
    """Invoke workspace ``predict.py`` per contract; return the npz arrays."""
    workspace = Path(workspace)
    with tempfile.TemporaryDirectory(dir=workspace) as td:
        inp = Path(td) / "params.json"
        out = Path(td) / "pred.npz"
        inp.write_text(json.dumps(params), encoding="utf-8")
        proc = subprocess.run(
            [python, "predict.py", "--input", str(inp), "--output", str(out)],
            cwd=workspace,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
        )
        if proc.returncode != 0:
            raise RuntimeError(
                f"predict.py exit {proc.returncode}\nstderr:\n{proc.stderr[-2000:]}"
            )
        with np.load(out) as npz:
            return {k: np.array(npz[k]) for k in npz.files}


def _check_predict(workspace: Path, grid: dict, report: ContractReport,
                   timeout_seconds: int) -> None:
    probe = [
        {"r0": 0.45, "a": 0.15, "kappa": 1.3, "delta": 0.2, "Ip": 140e3},
        {"r0": 0.40, "a": 0.12, "kappa": 1.1, "delta": 0.1, "Ip": 100e3},
        {"r0": 0.50, "a": 0.18, "kappa": 1.5, "delta": 0.3, "Ip": 180e3},
    ]
    try:
        arrays = run_predict(workspace, probe, timeout_seconds=timeout_seconds)
    except Exception as exc:  # noqa: BLE001
        report.set("predict_runs", False, f"{type(exc).__name__}: {exc}")
        return
    report.set("predict_runs", True)

    R_ref, Z_ref = grid_axes(grid)
    psi = arrays.get("psi")
    ok_shape = psi is not None and psi.shape == (len(probe), len(Z_ref), len(R_ref))
    report.set(
        "predict_shape", ok_shape,
        "" if ok_shape else f"psi shape {None if psi is None else psi.shape} "
        f"!= {(len(probe), len(Z_ref), len(R_ref))}",
    )
    R, Z = arrays.get("R"), arrays.get("Z")
    ok_grid = (
        R is not None and Z is not None
        and R.shape == R_ref.shape and Z.shape == Z_ref.shape
        and np.allclose(R, R_ref, atol=GRID_ATOL)
        and np.allclose(Z, Z_ref, atol=GRID_ATOL)
    )
    report.set("predict_grid", ok_grid, "" if ok_grid else "R/Z axes differ from the frozen grid")


def validate_deliverables(
    workspace: Path,
    task: TaskSpec,
    *,
    grid_json: Optional[Path] = None,
    run_predict_check: bool = True,
    predict_timeout: int = 600,
) -> ContractReport:
    workspace = Path(workspace)
    report = ContractReport()

    for rel in task.expected_artifacts:
        p = workspace / rel
        report.set(f"artifact:{rel}", p.is_file() and p.stat().st_size > 0)

    if "report.json" in task.expected_artifacts and (workspace / "report.json").is_file():
        _check_report_json(workspace / "report.json", report)

    if task.access_level == "L3":
        offenders = audit_no_autotokamak_import(workspace)
        report.set(
            "no_autotokamak_import", not offenders,
            f"offenders: {offenders}" if offenders else "",
        )

    if run_predict_check and (workspace / "predict.py").is_file():
        _check_predict(workspace, load_grid(grid_json), report, predict_timeout)

    return report


def rel_l2_errors(psi_pred: np.ndarray, psi_true: np.ndarray) -> np.ndarray:
    """Per-sample relative L2 over the finite ground-truth grid points."""
    errs = []
    for pred, true in zip(psi_pred, psi_true):
        mask = np.isfinite(true)
        denom = np.linalg.norm(true[mask])
        num = np.linalg.norm(np.nan_to_num(pred[mask] - true[mask]))
        errs.append(num / denom if denom > 0 else np.inf)
    return np.array(errs)


def score_against_frozen(
    workspace: Path,
    test_set_h5: Path,
    *,
    predict_timeout: int = 3600,
) -> dict[str, Any]:
    """Head-to-head relative-L2 vs the frozen test set (bench freeze-testset)."""
    from autotokamak.data.h5io import read_h5_arrays
    from autotokamak.surrogate.dataset import PARAM_ORDER

    arrays_h5 = read_h5_arrays(test_set_h5)
    ok = np.asarray(arrays_h5.success, dtype=bool)
    psi_true = arrays_h5.psi[ok]
    records = [
        {p: float(arrays_h5.inputs[p][i]) for p in PARAM_ORDER}
        for i in np.flatnonzero(ok)
    ]
    arrays = run_predict(Path(workspace), records, timeout_seconds=predict_timeout)
    errs = rel_l2_errors(arrays["psi"], psi_true)
    finite = errs[np.isfinite(errs)]
    return {
        "n_test": int(len(errs)),
        "n_scored": int(len(finite)),
        "test_rel_l2": {
            "mean": float(np.mean(finite)) if finite.size else None,
            "median": float(np.median(finite)) if finite.size else None,
            "p90": float(np.percentile(finite, 90)) if finite.size else None,
        },
    }
